
import { PrismaClient, Role } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding database...')

  // 1. Users
  const password = "Password123!" // In a real app, hash this! We'll do it in the Auth provider or simple hook if needed. 
  // NOTE: For NextAuth Credentials with simple logic, we might just store plain text for this MVP demo if we don't implement hashing in the seed.
  // BUT proper way is to use bcrypt. Let's assume the auth handler will verify against this string for now or we hash it.
  // For MVP speed ensuring "npm install" works without extra bcrypt setup if possible, or just add it.
  // Let's stick to simple text for the MVP seed, assuming the credential provider will compare directly or we'll add slight complexity later.
  // Actually, standard practice is bcrypt. I will leave it plain here and handle it in the auth options.

  const alice = await prisma.user.upsert({
    where: { email: 'alice@example.com' },
    update: {},
    create: {
      email: 'alice@example.com',
      name: 'Alice User',
      password,
      role: Role.USER,
    },
  })

  const reviewer = await prisma.user.upsert({
    where: { email: 'reviewer@example.com' },
    update: {},
    create: {
      email: 'reviewer@example.com',
      name: 'Bob Reviewer',
      password,
      role: Role.REVIEWER,
    },
  })

  const admin = await prisma.user.upsert({
    where: { email: 'admin@example.com' },
    update: {},
    create: {
      email: 'admin@example.com',
      name: 'Charlie Admin',
      password,
      role: Role.ADMIN,
    },
  })

  // 2. Action Types
  const actions = [
    { code: 'BIKE_TO_CAMPUS', title: 'Bike to Campus', baseCredits: 10 },
    { code: 'PUBLIC_TRANSIT', title: 'Take Public Transit', baseCredits: 15 },
    { code: 'ENERGY_SCREENSHOT', title: 'Energy Usage Screenshot', baseCredits: 20 },
  ]

  for (const action of actions) {
    await prisma.actionType.upsert({
      where: { code: action.code },
      update: {},
      create: action,
    })
  }

  // 3. Rewards
  const rewards = [
    { title: 'Campus Café $2 off', description: 'Get a discount on your coffee', cost: 40 },
    { title: 'Raffle Entry', description: 'Win a solar charger', cost: 25 },
    { title: 'Donate to Sustainability Fund', description: 'Support local green projects', cost: 30 },
  ]

  for (const r of rewards) {
    // Upsert by checking if one exists with same title (not unique constraints but good enough for seed)
    const existing = await prisma.reward.findFirst({ where: { title: r.title } })
    if (!existing) {
      await prisma.reward.create({ data: r })
    }
  }

  // 4. Lessons
  const lessons = [
    {
      title: 'Carbon Footprint 101',
      contentMd: '# Understanding Carbon Footprint\n\nYour carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by your actions.\n\n### Key Takeaways\n- Transportation is a major contributor.\n- Diet choices matter.\n- Energy efficiency at home helps.',
      questions: [
        { question: 'What gas is a primary component of carbon footprint?', options: ['Oxygen', 'Carbon Dioxide', 'Helium'], correctIndex: 1 },
        { question: 'Which sector is a major contributor?', options: ['Transportation', 'Knitting', 'Reading'], correctIndex: 0 },
        { question: 'Does home energy efficiency help?', options: ['Yes', 'No', 'Only on Tuesdays'], correctIndex: 0 },
      ]
    },
    {
      title: 'Recycling Basics',
      contentMd: '# Recycling Done Right\n\nNot everything can be recycled. Initial sorting is crucial.\n\n### Rules\n1. Clean your recyclables.\n2. Separate paper and plastic.\n3. Check local guidelines.',
      questions: [
        { question: 'Should you clean recyclables?', options: ['No', 'Yes', 'Depends on color'], correctIndex: 1 },
        { question: 'Can everything be recycled?', options: ['Yes', 'No', 'Maybe'], correctIndex: 1 },
        { question: 'What should you separate?', options: ['Paper and Plastic', 'Water and Oil', 'Socks'], correctIndex: 0 },
      ]
    },
    {
      title: 'Energy Conservation',
      contentMd: '# Saving Energy\n\nSimple habits save power.\n\n- Turn off lights.\n- Unplug electronics.\n- Use natural light.',
      questions: [
        { question: 'What should you do when leaving a room?', options: ['Turn off lights', 'Leave them on', 'Dance'], correctIndex: 0 },
        { question: 'What uses phantom power?', options: ['Unplugged devices', 'Plugged in electronics', 'Books'], correctIndex: 1 },
        { question: 'Is natural light good?', options: ['Yes', 'No', 'Harmful'], correctIndex: 0 },
      ]
    }
  ]

  for (const l of lessons) {
    const lesson = await prisma.lesson.create({
      data: {
        title: l.title,
        contentMd: l.contentMd,
      }
    })
    
    await prisma.quiz.create({
      data: {
        lessonId: lesson.id,
        questionsJson: JSON.stringify(l.questions)
      }
    })
  }

  console.log('Seeding completed.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
